/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPersetujuanRouteImport } from './routes/_authenticated/persetujuan'
import { Route as AuthenticatedPermintaanRouteImport } from './routes/_authenticated/permintaan'
import { Route as AuthenticatedPenggunaRouteImport } from './routes/_authenticated/pengguna'
import { Route as AuthenticatedPengaturanRouteImport } from './routes/_authenticated/pengaturan'
import { Route as AuthenticatedNotifikasiRouteImport } from './routes/_authenticated/notifikasi'
import { Route as AuthenticatedLaporanRouteImport } from './routes/_authenticated/laporan'
import { Route as AuthenticatedKategoriRouteImport } from './routes/_authenticated/kategori'
import { Route as AuthenticatedDataBarangRouteImport } from './routes/_authenticated/data-barang'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedBarangMasukRouteImport } from './routes/_authenticated/barang-masuk'
import { Route as AuthenticatedBarangKeluarRouteImport } from './routes/_authenticated/barang-keluar'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPersetujuanRoute =
  AuthenticatedPersetujuanRouteImport.update({
    id: '/persetujuan',
    path: '/persetujuan',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPermintaanRoute = AuthenticatedPermintaanRouteImport.update({
  id: '/permintaan',
  path: '/permintaan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPenggunaRoute = AuthenticatedPenggunaRouteImport.update({
  id: '/pengguna',
  path: '/pengguna',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPengaturanRoute = AuthenticatedPengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotifikasiRoute = AuthenticatedNotifikasiRouteImport.update({
  id: '/notifikasi',
  path: '/notifikasi',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLaporanRoute = AuthenticatedLaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKategoriRoute = AuthenticatedKategoriRouteImport.update({
  id: '/kategori',
  path: '/kategori',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDataBarangRoute = AuthenticatedDataBarangRouteImport.update({
  id: '/data-barang',
  path: '/data-barang',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBarangMasukRoute =
  AuthenticatedBarangMasukRouteImport.update({
    id: '/barang-masuk',
    path: '/barang-masuk',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBarangKeluarRoute =
  AuthenticatedBarangKeluarRouteImport.update({
    id: '/barang-keluar',
    path: '/barang-keluar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/barang-keluar': typeof AuthenticatedBarangKeluarRoute
  '/barang-masuk': typeof AuthenticatedBarangMasukRoute
  '/chat': typeof AuthenticatedChatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/data-barang': typeof AuthenticatedDataBarangRoute
  '/kategori': typeof AuthenticatedKategoriRoute
  '/laporan': typeof AuthenticatedLaporanRoute
  '/notifikasi': typeof AuthenticatedNotifikasiRoute
  '/pengaturan': typeof AuthenticatedPengaturanRoute
  '/pengguna': typeof AuthenticatedPenggunaRoute
  '/permintaan': typeof AuthenticatedPermintaanRoute
  '/persetujuan': typeof AuthenticatedPersetujuanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/barang-keluar': typeof AuthenticatedBarangKeluarRoute
  '/barang-masuk': typeof AuthenticatedBarangMasukRoute
  '/chat': typeof AuthenticatedChatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/data-barang': typeof AuthenticatedDataBarangRoute
  '/kategori': typeof AuthenticatedKategoriRoute
  '/laporan': typeof AuthenticatedLaporanRoute
  '/notifikasi': typeof AuthenticatedNotifikasiRoute
  '/pengaturan': typeof AuthenticatedPengaturanRoute
  '/pengguna': typeof AuthenticatedPenggunaRoute
  '/permintaan': typeof AuthenticatedPermintaanRoute
  '/persetujuan': typeof AuthenticatedPersetujuanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/barang-keluar': typeof AuthenticatedBarangKeluarRoute
  '/_authenticated/barang-masuk': typeof AuthenticatedBarangMasukRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/data-barang': typeof AuthenticatedDataBarangRoute
  '/_authenticated/kategori': typeof AuthenticatedKategoriRoute
  '/_authenticated/laporan': typeof AuthenticatedLaporanRoute
  '/_authenticated/notifikasi': typeof AuthenticatedNotifikasiRoute
  '/_authenticated/pengaturan': typeof AuthenticatedPengaturanRoute
  '/_authenticated/pengguna': typeof AuthenticatedPenggunaRoute
  '/_authenticated/permintaan': typeof AuthenticatedPermintaanRoute
  '/_authenticated/persetujuan': typeof AuthenticatedPersetujuanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/barang-keluar'
    | '/barang-masuk'
    | '/chat'
    | '/dashboard'
    | '/data-barang'
    | '/kategori'
    | '/laporan'
    | '/notifikasi'
    | '/pengaturan'
    | '/pengguna'
    | '/permintaan'
    | '/persetujuan'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/barang-keluar'
    | '/barang-masuk'
    | '/chat'
    | '/dashboard'
    | '/data-barang'
    | '/kategori'
    | '/laporan'
    | '/notifikasi'
    | '/pengaturan'
    | '/pengguna'
    | '/permintaan'
    | '/persetujuan'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/barang-keluar'
    | '/_authenticated/barang-masuk'
    | '/_authenticated/chat'
    | '/_authenticated/dashboard'
    | '/_authenticated/data-barang'
    | '/_authenticated/kategori'
    | '/_authenticated/laporan'
    | '/_authenticated/notifikasi'
    | '/_authenticated/pengaturan'
    | '/_authenticated/pengguna'
    | '/_authenticated/permintaan'
    | '/_authenticated/persetujuan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/persetujuan': {
      id: '/_authenticated/persetujuan'
      path: '/persetujuan'
      fullPath: '/persetujuan'
      preLoaderRoute: typeof AuthenticatedPersetujuanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/permintaan': {
      id: '/_authenticated/permintaan'
      path: '/permintaan'
      fullPath: '/permintaan'
      preLoaderRoute: typeof AuthenticatedPermintaanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pengguna': {
      id: '/_authenticated/pengguna'
      path: '/pengguna'
      fullPath: '/pengguna'
      preLoaderRoute: typeof AuthenticatedPenggunaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pengaturan': {
      id: '/_authenticated/pengaturan'
      path: '/pengaturan'
      fullPath: '/pengaturan'
      preLoaderRoute: typeof AuthenticatedPengaturanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifikasi': {
      id: '/_authenticated/notifikasi'
      path: '/notifikasi'
      fullPath: '/notifikasi'
      preLoaderRoute: typeof AuthenticatedNotifikasiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/laporan': {
      id: '/_authenticated/laporan'
      path: '/laporan'
      fullPath: '/laporan'
      preLoaderRoute: typeof AuthenticatedLaporanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kategori': {
      id: '/_authenticated/kategori'
      path: '/kategori'
      fullPath: '/kategori'
      preLoaderRoute: typeof AuthenticatedKategoriRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/data-barang': {
      id: '/_authenticated/data-barang'
      path: '/data-barang'
      fullPath: '/data-barang'
      preLoaderRoute: typeof AuthenticatedDataBarangRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/barang-masuk': {
      id: '/_authenticated/barang-masuk'
      path: '/barang-masuk'
      fullPath: '/barang-masuk'
      preLoaderRoute: typeof AuthenticatedBarangMasukRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/barang-keluar': {
      id: '/_authenticated/barang-keluar'
      path: '/barang-keluar'
      fullPath: '/barang-keluar'
      preLoaderRoute: typeof AuthenticatedBarangKeluarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBarangKeluarRoute: typeof AuthenticatedBarangKeluarRoute
  AuthenticatedBarangMasukRoute: typeof AuthenticatedBarangMasukRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDataBarangRoute: typeof AuthenticatedDataBarangRoute
  AuthenticatedKategoriRoute: typeof AuthenticatedKategoriRoute
  AuthenticatedLaporanRoute: typeof AuthenticatedLaporanRoute
  AuthenticatedNotifikasiRoute: typeof AuthenticatedNotifikasiRoute
  AuthenticatedPengaturanRoute: typeof AuthenticatedPengaturanRoute
  AuthenticatedPenggunaRoute: typeof AuthenticatedPenggunaRoute
  AuthenticatedPermintaanRoute: typeof AuthenticatedPermintaanRoute
  AuthenticatedPersetujuanRoute: typeof AuthenticatedPersetujuanRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBarangKeluarRoute: AuthenticatedBarangKeluarRoute,
  AuthenticatedBarangMasukRoute: AuthenticatedBarangMasukRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDataBarangRoute: AuthenticatedDataBarangRoute,
  AuthenticatedKategoriRoute: AuthenticatedKategoriRoute,
  AuthenticatedLaporanRoute: AuthenticatedLaporanRoute,
  AuthenticatedNotifikasiRoute: AuthenticatedNotifikasiRoute,
  AuthenticatedPengaturanRoute: AuthenticatedPengaturanRoute,
  AuthenticatedPenggunaRoute: AuthenticatedPenggunaRoute,
  AuthenticatedPermintaanRoute: AuthenticatedPermintaanRoute,
  AuthenticatedPersetujuanRoute: AuthenticatedPersetujuanRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
